..outputs/lda_trained_model.pickle ..outputs/lda_topic_dict.pickle: lda_topics.py ..outputs/X_train_count.pickle ..outputs/X_train_feature_names.pickle
	python3 lda_topics.py ..outputs/X_train_count.pickle ..outputs/X_train_feature_names.pickle ..outputs/lda_trained_model.pickle ..outputs/lda_topic_dict.pickle
