../outputs/svm.csv: svm.py ../outputs/X_train_tfidf.pickle ../outputs/X_test_tfidf.pickle ../outputs/y_train.npy ../outputs/y_test.npy ../outputs/A_test_tfidf.pickle
	python3 svm.py ../outputs/X_train_tfidf.pickle ../outputs/X_test_tfidf.pickle ../outputs/y_train.npy ../outputs/y_test.npy ../outputs/A_test_tfidf.pickle ../outputs/svm.csv
